spring:
  application:
    name: melody-eureka-client-provider
server:
  port: 8082
eureka:
  instance:
    hostname: melody.test.com
  client: 
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
